version: '3.8'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: films_app
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_net
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=films
            - DB_USERNAME=films
            - DB_PASSWORD=secret
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: films_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: films
            MYSQL_USER: films
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: films_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge

volumes:
    db_data:
